### ISSUE TITLE
Support searches from web interface (chorus)

### ISSUE THREAD

**Issue by avtoso** [bromix/plugin.audio.soundcloud#15]
I am unable to search using the SoundCloud plugin from the chorus web interface. Explore works fine.

Steps to reproduce:
1) Install chorus, configure as web interface
2) Navigate to Files -> AddOns -> SoundCloud
3) Press magnifying glass to get search dialog, search for any string. Nothing happens.
4) Switch to Kodi interface, see error "Mapping for path '/SearchTracks' not found"

Alternatively, do the same except:
3) Press the explicit "search" option underneath SoundCloud plugin, search for any string. Nothing happens.
4) Switch to Kodi interface, see different error "Mapping for path 'Search+kodion/search/list/' not found"

Since the search works fine within the plugin, I assume this is some mismatch in the URL structure exported from abstract_provider.py vs that expected by Chorus. I'm not familiar with Kodi plugins though, so not really sure how to fix it.

**Comment by bromix** [comment]
It's the other way arround ;) Chorus is calling the addon wrong. Like the exception states:
'SearchTracks' isn't support as a valid URI for the addon.
The addon is a complete rewrite and the old URIs aren't supported anymore (because I can't know any End-Point for some thirdparty software). Please contact the developer of chorus to look into it.

**Comment by avtoso** [comment]
Thanks :) I was not sure where to report this. I'll bring it up with the chorus devs.

Thanks for your great addon!
