### ISSUE TITLE
Crash on when starting to play a file

### ISSUE THREAD

**Issue by Finnitio** [bromix/plugin.audio.soundcloud#23]
When I start to play any file on soundcloud, via the GUI or externally via a remote soundcloud crashes and kodi freezes at 100% cpu usage and memory usage in creases. 

For files < 10 min it eventually starts playing. For sets it crashes at some point.

On raspberry pi 2, with latest raspbian and kodi. Reinstalled the plugin but that did't change anything.

**Comment by bromix** [comment]
A log would be nice ;) also RasPi 2 has a lot of problems. Have testet other addons add well?

**Comment by Finnitio** [comment]
Sorry new to linux, if you are more specific i will provide the log :).
Other addons like youtube for example ;), a runing without problems

**Comment by bromix** [comment]
http://kodi.wiki/view/Log_file

But this will be a problem of your RasPi 2...not the addon...otherwise I would have more complains like this one ;) Sorry, I can't provide help or support for RasPi 2 (or the many other platforms...I would go nuts;) ) in this manner. Please find help in a RadPi 2 forum/board.
